version: '3.8'
services:
  db:
    image: postgres:13
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'anna'
      POSTGRES_PASSWORD: '1111'
      POSTGRES_DB: 'roulette'

  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
        - 5672:5672
      networks:
        - rabbitmq_go_net

networks:
    rabbitmq_go_net:
      driver: bridge